sudo: false
language: ruby
rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3.1'
  - 'jruby-9.1.2.0'
matrix:
    allow_failures:
        - rvm: 'jruby-9.1.2.0'

cache: bundler

install:
    - gem install bundler
    # Some tests expect gems to be present in vendor/bundle
    - bundler install --path vendor/bundle
script:
    - bundler exec rake
    - bundler exec rake test
